name: artic
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - bcftools
  - biopython
  - bwa
  - clair3>=2.0.0
  - clint
  - htslib
  - minimap2
  - mafft
  - pandas
  - pip
  - pysam
  - pytest
  - requests
  - samtools
  - tqdm
  - seqtk
  - align_trim>=1.1.0
  - primalbedtools>=1.0.0
