"""minion_validator.py runs the functional tests of the minion pipeline, for both nanopolish and medaka workflows.

For each test dataset, it will make the following checks for each workflow:

    * check for existence of the final consensus sequence
    * check the final consensus matches the expected consensus
    * check for existence of the final VCF file (generated by artic_vcf_filter)
    * check all expected variants are reported
    * check no unexpected variants are reported
    * if there is an expected deletion, the consensus sequence will be checked for it's absence

NOTE:

    * only a basic grep is used for checking the deletion in the consensus - test will fail if deletion sequence is present multiple times (I should improve this part of the test...)

"""

from Bio import SeqIO
from tqdm import tqdm
import glob
import os
import pathlib
import pytest
import shutil
import tempfile
import unittest
import requests
import sys
import tarfile
import pysam


def _var_type(rec):
    ref = rec.ref
    alt = (rec.alts or (".",))[0]
    if alt == ".":
        return "unknown"
    if len(ref) == 1 and len(alt) == 1:
        return "snp"
    return "indel"


def _is_snp(rec):
    alt = (rec.alts or (".",))[0]
    return len(rec.ref) == 1 and len(alt) == 1


def _is_indel(rec):
    alt = (rec.alts or (".",))[0]
    return len(rec.ref) != len(alt)


def _is_deletion(rec):
    alt = (rec.alts or (".",))[0]
    return len(rec.ref) > len(alt)


from artic import pipeline

# help pytest resolve where test data is kept
dataDir = str(pathlib.Path(__file__).parent.parent) + "/test-data/"

# testData is a lookup of sampleIDs to download urls
testData = {
    "MT007544": "https://raw.githubusercontent.com/artic-network/fieldbioinformatics/master/test-data/MT007544/MT007544.fastq",
    "CVR1": "https://artic.s3.climb.ac.uk/validation-sets/CVR1.tgz",
    "NRW01": "http://artic.s3.climb.ac.uk/validation-teams/NRW01.tgz",
    "SP1": "http://artic.s3.climb.ac.uk/validation-teams/SP1.tgz",
}

# refConsensuses is a nested dict of sample IDs and their expected consensus sequences from the nanopolish workflow
refConsensuses = {
    "CVR1": dataDir + "consensus-sequences/CVR1.consensus.fasta",
    "NRW01": dataDir + "consensus-sequences/NRW01.consensus.fasta",
    "SP1": dataDir + "consensus-sequences/SP1.consensus.fasta",
}

# refMedakaConsensuses is a nested dict of sample IDs and their expected consensus sequences from the medaka workflow
refMedakaConsensuses = {
    "MT007544": dataDir + "consensus-sequences/MT007544.consensus.medaka.fasta",
    "CVR1": dataDir + "consensus-sequences/CVR1.consensus.medaka.fasta",
    "NRW01": dataDir + "consensus-sequences/NRW01.consensus.medaka.fasta",
    "SP1": dataDir + "consensus-sequences/SP1.consensus.medaka.fasta",
}

# clair3TestVariants is a nested dict of sample IDs and their expected variants when using the clair3 workflow
clair3TestVariants = {
    "CVR1": {
        # pos: (ref, alt, type, count)
        241: ["C", "T", "snp", 1],
        3037: ["C", "T", "snp", 1],
        12733: [
            "C",
            "T",
            "snp",
            1,
        ],
        14408: ["C", "T", "snp", 1],
        23403: ["A", "G", "snp", 1],
        27752: ["C", "T", "snp", 1],
        28881: ["G", "A", "snp", 1],
        28882: ["G", "A", "snp", 1],
        28883: ["G", "C", "snp", 1],
    },
    "NRW01": {
        1440: ["G", "A", "snp", 1],
        2891: ["G", "A", "snp", 1],
        4655: ["C", "T", "snp", 1],
        8422: ["G", "A", "snp", 1],
        22323: ["C", "T", "snp", 1],
        29546: ["C", "A", "snp", 2],
    },
    "SP1": {
        241: ["C", "T", "snp", 1],
        14408: ["C", "T", "snp", 1],
        23403: ["A", "G", "snp", 1],
    },
}

# extraFlags is a way to add extra sample-specific commands to the validation test cmd
extraFlags = {
    "clair3": {
        "SP1": ["--no-frameshifts"],
        "CVR1": ["--no-frameshifts"],
    },
    "clair3_allow_mismatches": {"CVR1": ["--allow-mismatched-primers"]},
}


# dataChecker will run before the tests and download all the test datasets if not present
def dataChecker():
    print("checking for validation datasets...")
    for sampleID, url in testData.items():
        targetPath = dataDir + sampleID
        if not os.path.exists(targetPath):
            print("\tno data for {}".format(sampleID))
            print("\tmaking dir at {}".format(targetPath))
            os.mkdir(targetPath)
            print("\tdownloading from {}".format(url))
            try:
                download(url, dataDir, sampleID)
            except Exception as e:
                print("download failed: ", e)
                sys.exit(1)
        else:
            print("\tfound data dir for {}".format(sampleID))
    print("validation datasets ready\n")


# download will download and untar a test dataset
def download(url, dataDir, sampleID):
    filename = url.rsplit("/", 1)[1]
    with open(f"{dataDir}/{filename}", "wb+") as f:
        response = requests.get(url, stream=True)
        total = int(response.headers.get("content-length"))
        if total is None:
            f.write(response.content)
        else:
            with tqdm(total=total, unit="B", unit_scale=True, desc=filename) as pbar:
                for data in tqdm(response.iter_content(chunk_size=1024)):
                    f.write(data)
                    pbar.update(1024)

    tar = tarfile.open(dataDir + "/" + filename, "r:gz")
    tar.extractall(dataDir)
    tar.close()
    os.remove(dataDir + "/" + filename)


# genCommand will create the minion command for the requested workflow (nanopolish or medaka)
def genCommand(sampleID, workflow):
    cmd = [
        "minion",
        "--threads",
        "2",
        "--linearise-fasta",
        "--read-file",
        dataDir + sampleID + "/" + sampleID + ".fastq",
        "--scheme-directory",
        dataDir + "primer-schemes",
    ]

    if workflow == "clair3" or workflow == "clair3_allow_mismatches":
        cmd.append("--model")
        cmd.append("r941_prom_hac_g360+g422")

    if sampleID in extraFlags[workflow]:
        for flag in extraFlags[workflow][sampleID]:
            cmd.append(flag)

    cmd.append("--scheme-name")
    cmd.append("SARS-CoV-2")
    cmd.append("--scheme-version")
    cmd.append("v1.0.0")
    cmd.append("--scheme-length")
    cmd.append("400")
    cmd.append(sampleID)
    return cmd


# cleanUp will remove all files generated by the pipeline for a given sampleID
def cleanUp(sampleID):
    fileList = glob.glob("{}*".format(sampleID))
    for filePath in fileList:
        try:
            if os.path.isdir(filePath):
                shutil.rmtree(filePath)
            else:
                os.remove(filePath)
        except Exception:
            sys.stderr.write(f"Error while deleting file : {filePath}")


# checkConsensus will return 1 if a subsequence is present in a consensus file, or 0 if absent
def checkConsensus(consensusFile, subSeq):
    for record in SeqIO.parse(open(consensusFile, "r"), "fasta"):
        if subSeq in record.seq:
            return 1
    return 0


# runner is the test runner
def runner(workflow, sampleID):

    if workflow == "clair3":
        data = clair3TestVariants
    elif workflow == "clair3_allow_mismatches":
        data = clair3TestVariants
    elif workflow == "medaka":
        data = medakaTestVariants
    else:
        sys.stderr.write("invalid workflow specified")
        assert False

    if sampleID not in data:
        sys.stderr.write("no test data for {}".format(sampleID))
        assert False

    expVariants = data[sampleID]

    # check the number of validation datasets requested
    # counter = numValidations
    # if (numValidations < 0) or (numValidations > len(testData)):
    #     counter = len(testData)

    # generate the command
    cmd = genCommand(sampleID, workflow)

    # setup and run the minion parser
    parser = pipeline.init_pipeline_parser()

    # parse the arguments
    try:
        args = parser.parse_args(cmd)
    except SystemExit:
        sys.stderr.write("failed to parse valid command for `artic minion`")
        assert False

    # run the minion pipeline
    try:
        args.func(parser, args)
    except SystemExit:
        sys.stderr.write("artic minion exited early with an error")
        assert False

    # check the ARTIC consensus was created
    consensusFile = "%s.consensus.fasta" % sampleID
    assert os.path.exists(consensusFile), "no consensus produced for {}".format(
        sampleID
    )
    testSeqs = SeqIO.parse(open(consensusFile, "r"), "fasta")
    testConsensus = next(testSeqs)

    # check the ARTIC consensus sequence matches the one on record
    # if workflow == "medaka":
    #     refSeqs = SeqIO.parse(open(refMedakaConsensuses[sampleID], "r"), "fasta")
    # else:
    #     refSeqs = SeqIO.parse(open(refConsensuses[sampleID], "r"), "fasta")
    # refConsensus = next(refSeqs)
    # assert (
    #     testConsensus.seq == refConsensus.seq
    # ), "produced ARTIC consensus does not match expected consensus for {}".format(
    #     sampleID
    # )

    # check the ARTIC VCF was created
    vcfFile = "%s.normalised.vcf.gz" % sampleID
    assert os.path.exists(vcfFile), "no VCF produced for {}".format(sampleID)

    obs_variants = {}
    # open the VCF and check the reported variants match the expected
    for record in pysam.VariantFile(vcfFile):
        pos = record.pos
        alt = (record.alts or (".",))[0]
        obs_variants[pos] = [record.ref, alt, _var_type(record)]
        if pos in expVariants:
            assert (
                record.ref == expVariants[pos][0]
            ), "incorrect REF reported in VCF for {} at position {}".format(
                sampleID, pos
            )
            assert (
                alt == expVariants[pos][1]
            ), "incorrect ALT reported in VCF for {} at position {}".format(
                sampleID, pos
            )

            # if this is an expected deletion, check the consensus sequence for it's absence
            if expVariants[pos][2] == "del":
                assert (
                    checkConsensus(consensusFile, record.ref) == 0
                ), "expected deletion for {} was reported but was left in consensus".format(
                    sampleID
                )

                # also check that the VCF record is correctly labelled as DEL
                assert _is_deletion(
                    record
                ), "deletion for {} not formatted correctly in VCF".format(sampleID)

            # if this is an expected indel, check that the VCF record is correctly labelled as INDEL
            if expVariants[pos][2] == "indel":
                assert _is_indel(
                    record
                ), "indel for {} not formatted correctly in VCF".format(sampleID)

            # else, check that the VCF record is correctly labelled as SNP
            if expVariants[pos][2] == "snp":
                assert _is_snp(
                    record
                ), "snp for {} not formatted correctly in VCF".format(sampleID)

            # decrement/remove the variant from the expected list, so we can keep track of checked variants
            # expVariants[record.POS][3] -= 1
            # if expVariants[record.POS][3] == 0:
            #     del expVariants[record.POS]

        else:
            print(
                f"unexpected variant found for {sampleID}: {alt} at {pos}",
                file=sys.stderr,
            )
            assert False

    # check we've confirmed all the expected variants
    for key, val in expVariants.items():
        assert obs_variants.get(
            key
        ), f"expected variant not found for {sampleID}: {val[0]} -> {val[1]} at {key}"
        assert (
            val[0:2] == obs_variants[key][0:2]
        ), f"expected variant not found for {sampleID}: {val[0]} -> {val[1]} at {key}"

    # clean up pipeline files
    cleanUp(sampleID)


class TestMinion(unittest.TestCase):
    def setUp(self):
        dataChecker()

    def test_Clair3_CVR1_allow_primer_mismatches(self):
        runner("clair3_allow_mismatches", "CVR1")

    def test_Clair3_CVR1(self):
        runner("clair3", "CVR1")

    def test_Clair3_NRW01(self):
        runner("clair3", "NRW01")

    def test_Clair3_SP1(self):
        runner("clair3", "SP1")

    def test_Clair3_mixed_model_dir(self):
        """Clair3 must complete successfully when the model directory contains both
        PyTorch .pt files and TF checkpoint files (the migration scenario where a
        user has previously downloaded TF models into the same directory)."""
        conda_prefix = os.getenv("CONDA_PREFIX")
        if not conda_prefix:
            self.skipTest("CONDA_PREFIX not set")

        model_name = "r941_prom_hac_g360+g422"
        src_model_dir = os.path.join(conda_prefix, "bin", "models", model_name)
        if not os.path.isdir(src_model_dir):
            self.skipTest(f"Model {model_name} not found at {src_model_dir}")

        with tempfile.TemporaryDirectory() as tmp_models:
            # Copy the real PyTorch model files into the temp model dir
            dest_model_dir = os.path.join(tmp_models, model_name)
            shutil.copytree(src_model_dir, dest_model_dir)

            # Inject dummy TF checkpoint files alongside the real .pt files
            for fname in [
                "pileup.data-00000-of-00001",
                "pileup.index",
                "full_alignment.data-00000-of-00001",
                "full_alignment.index",
            ]:
                open(os.path.join(dest_model_dir, fname), "w").close()

            sampleID = "CVR1"
            cmd = genCommand(sampleID, "clair3") + ["--model-dir", tmp_models]

            parser = pipeline.init_pipeline_parser()
            args = parser.parse_args(cmd)

            try:
                args.func(parser, args)
            except SystemExit:
                self.fail(
                    "artic minion exited early — clair3 failed with a mixed TF/PyTorch model directory"
                )

            consensus = f"{sampleID}.consensus.fasta"
            self.assertTrue(
                os.path.exists(consensus),
                "No consensus produced when running clair3 with a mixed TF/PyTorch model directory",
            )
            cleanUp(sampleID)


@pytest.mark.slow
class TestMinionSpacedPaths(unittest.TestCase):
    """Regression: the full pipeline must complete when every path argument
    contains spaces — a common failure mode on WSL and Windows where user home
    directories or data directories often include spaces.

    Skipped automatically when the CVR1 test dataset or the clair3 model is
    not present (i.e. on a machine that hasn't been set up for validation).
    """

    MODEL_NAME = "r941_prom_hac_g360+g422"

    def setUp(self):
        dataChecker()

    def _find_model_dir(self):
        conda_prefix = os.getenv("CONDA_PREFIX")
        if not conda_prefix:
            self.skipTest("CONDA_PREFIX not set — cannot locate clair3 models")
        model_dir = os.path.join(conda_prefix, "bin", "models")
        if not os.path.isdir(os.path.join(model_dir, self.MODEL_NAME)):
            self.skipTest(
                f"Clair3 model '{self.MODEL_NAME}' not found at {model_dir} — "
                "run 'artic_get_models' first"
            )
        return model_dir

    def test_clair3_spaced_paths(self):
        """artic minion produces a consensus and VCF when every path — read
        file, primer scheme, model directory, and sample prefix — contains a
        space character.  This exercises every shlex.quote() call in minion.py.
        """
        model_dir = self._find_model_dir()

        sample_id = "CVR1"
        src_fastq = os.path.join(dataDir, sample_id, f"{sample_id}.fastq")
        if not os.path.exists(src_fastq):
            self.skipTest(f"CVR1 FASTQ not found at {src_fastq}")

        with tempfile.TemporaryDirectory() as tmpdir:
            # Create directories whose names contain spaces.
            data_dir = os.path.join(tmpdir, "artic data")
            output_dir = os.path.join(tmpdir, "artic output")
            scheme_dir = os.path.join(tmpdir, "primer schemes")
            models_dir = os.path.join(tmpdir, "clair3 models")
            for d in (data_dir, output_dir, scheme_dir, models_dir):
                os.makedirs(d)

            # Symlink the clair3 model into the spaced models directory so we
            # don't have to copy the (potentially large) model files.
            os.symlink(
                os.path.join(model_dir, self.MODEL_NAME),
                os.path.join(models_dir, self.MODEL_NAME),
            )

            # Copy the FASTQ to a filename that contains a space.
            spaced_fastq = os.path.join(data_dir, "sample reads.fastq")
            shutil.copy2(src_fastq, spaced_fastq)

            # Sample prefix: directory and basename both contain spaces.
            sample_prefix = os.path.join(output_dir, "my sample")

            cmd = [
                "minion",
                "--model",
                self.MODEL_NAME,
                "--model-dir",
                models_dir,
                "--read-file",
                spaced_fastq,
                "--scheme-name",
                "SARS-CoV-2",
                "--scheme-version",
                "v1.0.0",
                "--scheme-length",
                "400",
                "--scheme-directory",
                scheme_dir,
                "--threads",
                "2",
                "--linearise-fasta",
                "--no-frameshifts",
                sample_prefix,
            ]

            parser = pipeline.init_pipeline_parser()
            try:
                args = parser.parse_args(cmd)
            except SystemExit:
                self.fail("Failed to parse minion command with spaced paths")

            import io
            import contextlib

            stderr_buf = io.StringIO()
            try:
                with contextlib.redirect_stderr(stderr_buf):
                    args.func(parser, args)
            except SystemExit as e:
                stderr_text = stderr_buf.getvalue()

                # Also attach the pipeline log if it was written before the failure.
                log_file = f"{sample_prefix}.minion.log.txt"
                if os.path.exists(log_file):
                    with open(log_file) as lf:
                        log_text = lf.read()
                else:
                    log_text = "(log file not written)"

                self.fail(
                    f"artic minion exited with code {e.code} — "
                    "pipeline failed with spaces in paths\n\n"
                    f"--- stderr ---\n{stderr_text}\n"
                    f"--- log ({log_file}) ---\n{log_text}"
                )

            self.assertTrue(
                os.path.exists(f"{sample_prefix}.consensus.fasta"),
                "No consensus produced when running with spaced paths",
            )
            self.assertTrue(
                os.path.exists(f"{sample_prefix}.normalised.vcf.gz"),
                "No VCF produced when running with spaced paths",
            )
