name: fieldbioinformatics_unit_tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6"]
    steps:
      - uses: mamba-org/setup-micromamba@v1
        name: Setup dependencies
        with:
          environment-file: environment.yml
      - run: |
          pytest -s artic/*_unit_test.py
          ./test-runner.sh medaka
          ./test-runner.sh clair3
          pytest -s artic/minion_validator.py --workFlow medaka --numValidations 2
          pytest -s artic/minion_validator.py --workFlow clair3 --numValidations 2
